#!/bin/bash
echo "=========================================="
echo "Python 3.11 Installation Guide"
echo "=========================================="
echo ""
echo "I cannot install Homebrew automatically (requires your password)."
echo ""
echo "Please run these commands manually in Terminal:"
echo ""
echo "1. Install Homebrew:"
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "2. Install Python 3.11:"
echo "   brew install python@3.11"
echo ""
echo "3. Install backend dependencies:"
echo "   cd $(pwd)/backend"
echo "   python3.11 -m pip install -r requirements.txt"
echo "   python3.11 -m spacy download en_core_web_sm"
echo ""
echo "4. Start backend:"
echo "   python3.11 start_server.py"
echo ""
echo "See INSTALL_PYTHON311.md for detailed instructions."
echo "=========================================="
